# Sortowanie alfabetyczne endpointów (zamiast kolejno?ci w kodzie)
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha

# Domy?lne zwini?cie listy endpointów (czystszy widok na start)
springdoc.swagger-ui.doc-expansion=none

# Wy??czenie sekcji "Schemas" (modeli) na dole strony, je?li jej nie potrzebujesz
springdoc.swagger-ui.default-models-expand-depth=-1

# Zmiana ?cie?ki (je?li nie chcesz domy?lnego /swagger-ui.html)
springdoc.swagger-ui.path=/dokumentacja.html
springdoc.swagger-ui.layout=BaseLayout
springdoc.swagger-ui.filter=false